name: Daily Health Check
on:
  schedule:
    # Runs daily at midnight
    - cron: '0 0 * * *'

jobs:
  daily_health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check health
        uses: jtalk/url-health-check-action@v2
        with:
          url: "https://pokedex-fullstack-rafxar.herokuapp.com/health"
          max-attempts: 3
          retry-delay: 5
